### ISSUE TITLE
Strange conversion error/status message when converting this file

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#195]
Story:
The user inadvertently selected "current" for conversion on a file with the magnetometer disabled.  The status was changed to "failed".  The user, realizing their mistake, changed the output type to "Discrete Channels" and attempted to convert again.  This time a dialog box appeared:
![image](https://user-images.githubusercontent.com/3340259/64812499-55413880-d56d-11e9-8a8a-653c3c9b99e9.png)

The user selected "Yes" but the files still had a status of failed and they did not convert.  The user was confused.

**Comment by jeff101** [comment]
This brings up a question about how errors in general should be treated. If a file fails to convert, what should happen? I just added this new dialog box with a more detailed explanation for each file that fails to convert:
![image](https://user-images.githubusercontent.com/8093093/64869967-70b14f80-d610-11e9-8b44-9019d106787e.png)
We're now able to offer much more specific error messages for each failed file. The question is, what do we do after the OK button is clicked? The easiest option from my point of view is to just remove the failed files from the table. However, this doesn't allow the user a second chance to see which files didn't convert. If we leave the error files, what should happen to them when the "Convert" button is pressed again? Should their status be reset? Should they be ignored? What if, as in your example, the wrong output type was selected?

**Comment by jeff101** [comment]
How about this for a solution?
![image](https://user-images.githubusercontent.com/8093093/64875120-64ca8b00-d61a-11e9-94e0-e0e01f52495f.png)

**Comment by jeff101** [comment]
Fixed in #194

**Comment by Nickel33** [comment]
This is not quite fixed.  If the user inadvertently selects heading with the magnetometer disabled, an error is indicated (good) but when the output type is switched back to "discrete channels" the convert button no longer works.

**Comment by jeff101** [comment]
As per our phone conversation:
If a file has an error status, rather than just insisting that it be removed, also give the option to reset its status.

**Comment by jeff101** [comment]
![image](https://user-images.githubusercontent.com/8093093/65246882-62a27980-dabd-11e9-9a91-ddb37cee964e.png)

**Comment by Nickel33** [comment]
Verified fixed 0.6.2 RC4
